### ISSUE TITLE
Détails d'un talk : en appuyant à côté de l'étoile, elle clignote indéfiniement

### ISSUE THREAD

**Issue by g123k** [paug/android-app-makers-2017#11]
Cf vidéo (il faut laissé cliqué à gauche de l'étoile) :
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/246838/24354161/19814c4a-12f1-11e7-9a78-c5ccc9c5dfb4.gif)

**Comment by djavan-bertrand** [comment]
C'est reproductible? Je n'y arrive pas.

**Comment by g123k** [comment]
Oui dans 100% des cas sur mon Pixel (Android 7.1.1).
Commence par faire un appui long sur l'étoile et décale légèrement ton doigt à gauche.

**Comment by djavan-bertrand** [comment]
Ok!
Dès que tu enlèves ton doigt de l'écran ça s'arrête par contre non?

**Comment by g123k** [comment]
Oui c'est bien ça.
C'est la première fois que j'ai ce comportement, donc je ne pense pas que ce soit un problème de la Toolbar

**Comment by djavan-bertrand** [comment]
Une idée sur un truc que je fais mal?

- [J'affiche/cache les menu items en fonction de l'état de la session](https://github.com/paug/android-app-makers-2017/blob/master/app/src/main/java/fr/paug/androidmakers/ui/activity/DetailActivity.java#L170)
- [Après avoir reçu l'event onMenuItemSelected, je reload le menu](https://github.com/paug/android-app-makers-2017/blob/master/app/src/main/java/fr/paug/androidmakers/ui/activity/DetailActivity.java#L163)

**Comment by g123k** [comment]
Pour mes toggle, d'habitude je fais juste un seul bouton dont je change le texte et l'image dynamiquement. Et je n'ai jamais eu de problème avec.

Je pense que l'appel au invalidateOptionsMenu(), donne le clic à l'autre MenuItem, d'où la boucle infinie.

**Comment by g123k** [comment]
Je viens de relire mon code sur l'app FrAndroid et en fait je ne fais pas un return true, mais un return false dans le onOptionsItemSelected.

Je viens de tester dans ton code et ça marche bien comme ça.

**Comment by djavan-bertrand** [comment]
Testé dans l'app AndroidMakers, ça ne change rien '-_-

**Comment by g123k** [comment]
Tu l'as bien fait sur les 2 items du onOptionsItemSelected ?
