### ISSUE TITLE
Vue récréée inutilement

### ISSUE THREAD

**Issue by g123k** [paug/android-app-makers-2017#3]
Lorsqu'on clique sur un bouton de la BottomNavigationView, la vue est recréée si on est déjà sur l'écran. Il faudrait éviter ce comportement.

**Comment by wang-li** [comment]
Fixed by commit https://github.com/paug/android-app-makers-2017/commit/4773daa5dc16db43db20c46b006dfcc6f0a5b8e7

**Comment by benju69** [comment]
ok c'est mieux mais l'état des fragments est pas sauvegardé comme je t'ai dis
