### ISSUE TITLE
Agenda : le nom des salles n'a pas la même largeur

### ISSUE THREAD

**Issue by g123k** [paug/android-app-makers-2017#6]
![screenshot_20170327-101645 copy](https://cloud.githubusercontent.com/assets/246838/24347241/ede3b4ce-12d7-11e7-81b1-472a489365e9.png)

Il faudrait que les trois noms de salles aient la même largeur.

**Comment by djavan-bertrand** [comment]
On pourrait peut-être les mettre de toute la largeur de la colonne et sans alpha non?

**Comment by g123k** [comment]
Je pense que ce serait mieux aussi, là ça fait un peu bizarre.

**Comment by StanKocken** [comment]
Humm, vous pensez ? Je peux faire ça mais je trouve ça moins bien.
L'apha permet de faire des "tags" qui ne casse pas une partie de l'écran je trouve.
