### ISSUE TITLE
Détails d'un talk : pas d'état cliqué sur les réseaux sociaux

### ISSUE THREAD

**Issue by g123k** [paug/android-app-makers-2017#7]
![screenshot_20170327-102740](https://cloud.githubusercontent.com/assets/246838/24347389/7211e144-12d8-11e7-9f56-a2d149d51c51.png)

Les images des réseaux sociaux sont bien cliquables, mais il n'y a pas de ripple/background montrant l'état cliquable.

**Comment by djavan-bertrand** [comment]
Pareil pour les boutons de config wifi

**Comment by benju69** [comment]
les boutons de config wifi ? j'avais changé en un seul bouton

**Comment by djavan-bertrand** [comment]
Pardon, *le* bouton de config wifi :p

**Comment by benju69** [comment]
Vu que c'est un bouton c'est bon ^^

**Comment by djavan-bertrand** [comment]
ah sorry!

**Comment by benju69** [comment]
C'est fixé

**Comment by benju69** [comment]
https://github.com/paug/android-app-makers-2017/commit/d069473af931cf706b526b0e1aa75c766f21d708
