### ISSUE TITLE
Détails d'un talk : réseaux sociaux (navigateur vs Chrome custom tabs)

### ISSUE THREAD

**Issue by g123k** [paug/android-app-makers-2017#9]
![screenshot_20170327-102740](https://cloud.githubusercontent.com/assets/246838/24348704/e8dbb35a-12dc-11e7-8d63-ccdd4cb04427.png)

Sur l'onglet About, les liens sont ouverts via des Chrome Custom Tabs.
En revanche, les liens vers les réseaux sociaux d'un speaker ouvrent eux directement le navigateur.

Il faudrait uniformiser cela.

**Comment by benju69** [comment]
Sauf si on l'app, ça ouvre l'app...
Faudrait faire ça juste pour les sites webs

**Comment by g123k** [comment]
Perso ça ne me gêne pas que les apps s'ouvrent, au contraire

**Comment by n0tnull** [comment]
Cela a été corrigé, je ferme le ticket.
